name: Release Please

on:
  workflow_dispatch: # For manual runs
  release: # To update release PRs when one is merged
    types: [published]
  pull_request: # To handle the release label being removed
    types: [unlabeled]
  push: # Standard workflow
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
     - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
